/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IOrbitAttestation__factory } from "./IOrbitAttestation__factory";
export { OrbitAttestation__factory } from "./OrbitAttestation__factory";
