/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IOrbitAttestation } from "./IOrbitAttestation";
export type { OrbitAttestation } from "./OrbitAttestation";
export * as factories from "./factories";
export { IOrbitAttestation__factory } from "./factories/IOrbitAttestation__factory";
export { OrbitAttestation__factory } from "./factories/OrbitAttestation__factory";
