/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IOrbitAttestationInterface extends Interface {
  getFunction(
    nameOrSignature: "attest" | "getAttestation" | "isAttested"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Attestation"): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAttested",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAttested", data: BytesLike): Result;
}

export namespace AttestationEvent {
  export type InputTuple = [
    user: AddressLike,
    contentHash: BytesLike,
    timestamp: BigNumberish,
    storageRoot: string
  ];
  export type OutputTuple = [
    user: string,
    contentHash: string,
    timestamp: bigint,
    storageRoot: string
  ];
  export interface OutputObject {
    user: string;
    contentHash: string;
    timestamp: bigint;
    storageRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOrbitAttestation extends BaseContract {
  connect(runner?: ContractRunner | null): IOrbitAttestation;
  waitForDeployment(): Promise<this>;

  interface: IOrbitAttestationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [contentHash: BytesLike, storageRoot: string],
    [void],
    "nonpayable"
  >;

  getAttestation: TypedContractMethod<
    [contentHash: BytesLike],
    [
      [string, bigint, string] & {
        user: string;
        timestamp: bigint;
        storageRoot: string;
      }
    ],
    "view"
  >;

  isAttested: TypedContractMethod<[contentHash: BytesLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [contentHash: BytesLike, storageRoot: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [contentHash: BytesLike],
    [
      [string, bigint, string] & {
        user: string;
        timestamp: bigint;
        storageRoot: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isAttested"
  ): TypedContractMethod<[contentHash: BytesLike], [boolean], "view">;

  getEvent(
    key: "Attestation"
  ): TypedContractEvent<
    AttestationEvent.InputTuple,
    AttestationEvent.OutputTuple,
    AttestationEvent.OutputObject
  >;

  filters: {
    "Attestation(address,bytes32,uint256,string)": TypedContractEvent<
      AttestationEvent.InputTuple,
      AttestationEvent.OutputTuple,
      AttestationEvent.OutputObject
    >;
    Attestation: TypedContractEvent<
      AttestationEvent.InputTuple,
      AttestationEvent.OutputTuple,
      AttestationEvent.OutputObject
    >;
  };
}
